use lofty::tag::ItemKey;

#[allow(clippy::too_many_lines)]
#[must_use]
pub fn flag_to_item_key(flag: &str) -> Option<ItemKey> {
    let name = flag.trim_start_matches('-');
    match name {
        "album" => Some(ItemKey::AlbumTitle),
        "discsubtitle" => Some(ItemKey::SetSubtitle),
        "grouping" => Some(ItemKey::ContentGroup),
        "title" => Some(ItemKey::TrackTitle),
        "subtitle" => Some(ItemKey::TrackSubtitle),
        "work" => Some(ItemKey::Work),
        "movementname" => Some(ItemKey::Movement),
        "movement" => Some(ItemKey::MovementNumber),
        "movementtotal" => Some(ItemKey::MovementTotal),
        "releasecountry" => Some(ItemKey::ReleaseCountry),
        "albumsort" => Some(ItemKey::AlbumTitleSortOrder),
        "albumartistsort" => Some(ItemKey::AlbumArtistSortOrder),
        "titlesort" => Some(ItemKey::TrackTitleSortOrder),
        "artistsort" => Some(ItemKey::TrackArtistSortOrder),
        "composersort" => Some(ItemKey::ComposerSortOrder),
        "albumartist" => Some(ItemKey::AlbumArtist),
        "albumartists" => Some(ItemKey::AlbumArtists),
        "artist" => Some(ItemKey::TrackArtist),
        "artists" => Some(ItemKey::TrackArtists),
        "arranger" => Some(ItemKey::Arranger),
        "writer" => Some(ItemKey::Writer),
        "composer" => Some(ItemKey::Composer),
        "conductor" => Some(ItemKey::Conductor),
        "director" => Some(ItemKey::Director),
        "engineer" => Some(ItemKey::Engineer),
        "lyricist" => Some(ItemKey::Lyricist),
        "djmixer" => Some(ItemKey::MixDj),
        "mixer" => Some(ItemKey::MixEngineer),
        "performer" => Some(ItemKey::Performer),
        "producer" => Some(ItemKey::Producer),
        "publisher" => Some(ItemKey::Publisher),
        "remixer" => Some(ItemKey::Remixer),
        "discnumber" => Some(ItemKey::DiscNumber),
        "disctotal" => Some(ItemKey::DiscTotal),
        "tracknumber" => Some(ItemKey::TrackNumber),
        "tracktotal" => Some(ItemKey::TrackTotal),
        "rating" => Some(ItemKey::Popularimeter),
        "date" => Some(ItemKey::RecordingDate),
        "originaldate" => Some(ItemKey::OriginalReleaseDate),
        "releasedate" => Some(ItemKey::ReleaseDate),
        "isrc" => Some(ItemKey::Isrc),
        "barcode" => Some(ItemKey::Barcode),
        "acoustid-id" => Some(ItemKey::AcoustId),
        "acoustid-fingerprint" => Some(ItemKey::AcoustIdFingerprint),
        "catalognumber" => Some(ItemKey::CatalogNumber),
        "musicbrainz-trackid" => Some(ItemKey::MusicBrainzRecordingId),
        "musicbrainz-releasetrackid" => Some(ItemKey::MusicBrainzTrackId),
        "musicbrainz-albumid" => Some(ItemKey::MusicBrainzReleaseId),
        "musicbrainz-releasegroupid" => Some(ItemKey::MusicBrainzReleaseGroupId),
        "musicbrainz-artistid" => Some(ItemKey::MusicBrainzArtistId),
        "musicbrainz-albumartistid" => Some(ItemKey::MusicBrainzReleaseArtistId),
        "musicbrainz-workid" => Some(ItemKey::MusicBrainzWorkId),
        "releasetype" => Some(ItemKey::MusicBrainzReleaseType),
        "compilation" => Some(ItemKey::FlagCompilation),
        "podcast" => Some(ItemKey::FlagPodcast),
        "media" => Some(ItemKey::OriginalMediaType),
        "encodedby" => Some(ItemKey::EncodedBy),
        "encoder" => Some(ItemKey::EncoderSoftware),
        "encodersettings" => Some(ItemKey::EncoderSettings),
        "replaygain-album-gain" => Some(ItemKey::ReplayGainAlbumGain),
        "replaygain-album-peak" => Some(ItemKey::ReplayGainAlbumPeak),
        "replaygain-track-gain" => Some(ItemKey::ReplayGainTrackGain),
        "replaygain-track-peak" => Some(ItemKey::ReplayGainTrackPeak),
        "r128-track-gain" => Some(ItemKey::R128TrackGain),
        "r128-album-gain" => Some(ItemKey::R128AlbumGain),
        "genre" => Some(ItemKey::Genre),
        "color" => Some(ItemKey::Color),
        "mood" => Some(ItemKey::Mood),
        "bpm" => Some(ItemKey::Bpm),
        "initialkey" => Some(ItemKey::InitialKey),
        "copyright" => Some(ItemKey::CopyrightMessage),
        "license" => Some(ItemKey::License),
        "comment" => Some(ItemKey::Comment),
        "description" => Some(ItemKey::Description),
        "language" => Some(ItemKey::Language),
        "script" => Some(ItemKey::Script),
        "lyrics" => Some(ItemKey::Lyrics),
        _ => None,
    }
}

#[allow(clippy::too_many_lines)]
#[must_use]
pub const fn item_key_to_flag(key: ItemKey) -> &'static str {
    match key {
        ItemKey::AlbumTitle => "album",
        ItemKey::SetSubtitle => "discsubtitle",
        ItemKey::ContentGroup => "grouping",
        ItemKey::TrackTitle => "title",
        ItemKey::TrackSubtitle => "subtitle",
        ItemKey::Work => "work",
        ItemKey::Movement => "movementname",
        ItemKey::MovementNumber => "movement",
        ItemKey::MovementTotal => "movementtotal",
        ItemKey::ReleaseCountry => "releasecountry",
        ItemKey::AlbumTitleSortOrder => "albumsort",
        ItemKey::AlbumArtistSortOrder => "albumartistsort",
        ItemKey::TrackTitleSortOrder => "titlesort",
        ItemKey::TrackArtistSortOrder => "artistsort",
        ItemKey::ComposerSortOrder => "composersort",
        ItemKey::AlbumArtist => "albumartist",
        ItemKey::AlbumArtists => "albumartists",
        ItemKey::TrackArtist => "artist",
        ItemKey::TrackArtists => "artists",
        ItemKey::Arranger => "arranger",
        ItemKey::Writer => "writer",
        ItemKey::Composer => "composer",
        ItemKey::Conductor => "conductor",
        ItemKey::Director => "director",
        ItemKey::Engineer => "engineer",
        ItemKey::Lyricist => "lyricist",
        ItemKey::MixDj => "djmixer",
        ItemKey::MixEngineer => "mixer",
        ItemKey::Performer => "performer",
        ItemKey::Producer => "producer",
        ItemKey::Publisher | ItemKey::Label => "publisher",
        ItemKey::Remixer => "remixer",
        ItemKey::DiscNumber => "discnumber",
        ItemKey::DiscTotal => "disctotal",
        ItemKey::TrackNumber => "tracknumber",
        ItemKey::TrackTotal => "tracktotal",
        ItemKey::Popularimeter => "rating",
        ItemKey::RecordingDate | ItemKey::Year => "date",
        ItemKey::OriginalReleaseDate => "originaldate",
        ItemKey::ReleaseDate => "releasedate",
        ItemKey::Isrc => "isrc",
        ItemKey::Barcode => "barcode",
        ItemKey::AcoustId => "acoustid-id",
        ItemKey::AcoustIdFingerprint => "acoustid-fingerprint",
        ItemKey::CatalogNumber => "catalognumber",
        ItemKey::MusicBrainzRecordingId => "musicbrainz-trackid",
        ItemKey::MusicBrainzTrackId => "musicbrainz-releasetrackid",
        ItemKey::MusicBrainzReleaseId => "musicbrainz-albumid",
        ItemKey::MusicBrainzReleaseGroupId => "musicbrainz-releasegroupid",
        ItemKey::MusicBrainzArtistId => "musicbrainz-artistid",
        ItemKey::MusicBrainzReleaseArtistId => "musicbrainz-albumartistid",
        ItemKey::MusicBrainzWorkId => "musicbrainz-workid",
        ItemKey::MusicBrainzReleaseType => "releasetype",
        ItemKey::FlagCompilation => "compilation",
        ItemKey::FlagPodcast => "podcast",
        ItemKey::OriginalMediaType => "media",
        ItemKey::EncodedBy => "encodedby",
        ItemKey::EncoderSoftware => "encoder",
        ItemKey::EncoderSettings => "encodersettings",
        ItemKey::ReplayGainAlbumGain => "replaygain-album-gain",
        ItemKey::ReplayGainAlbumPeak => "replaygain-album-peak",
        ItemKey::ReplayGainTrackGain => "replaygain-track-gain",
        ItemKey::ReplayGainTrackPeak => "replaygain-track-peak",
        ItemKey::R128TrackGain => "r128-track-gain",
        ItemKey::R128AlbumGain => "r128-album-gain",
        ItemKey::Genre => "genre",
        ItemKey::Color => "color",
        ItemKey::Mood => "mood",
        ItemKey::Bpm | ItemKey::IntegerBpm => "bpm",
        ItemKey::InitialKey => "initialkey",
        ItemKey::CopyrightMessage => "copyright",
        ItemKey::License => "license",
        ItemKey::Comment => "comment",
        ItemKey::Description => "description",
        ItemKey::Language => "language",
        ItemKey::Script => "script",
        ItemKey::Lyrics | ItemKey::UnsyncLyrics => "lyrics",
        _ => "unknown",
    }
}

#[must_use]
pub const fn canonical_key(key: ItemKey) -> ItemKey {
    match key {
        ItemKey::UnsyncLyrics => ItemKey::Lyrics,
        ItemKey::IntegerBpm => ItemKey::Bpm,
        ItemKey::Label => ItemKey::Publisher,
        ItemKey::Year => ItemKey::RecordingDate,
        other => other,
    }
}
