[storage]
library_root = "/home/lewelove/dev/mpf2k-test-library/albums/"
library_export = "~/dev/mpf2k-test-library/metadata_output"

[generate]
supported_extensions = [".flac"]
grouping_keys = ["ALBUMARTIST", "ALBUM", "CUSTOM_ID"]
naming_separator = "_"
naming_sanitization_char = "_"

[compress.album]
layout = [
  "\n",
  "ALBUM",
  "ALBUMARTIST",
  "DATE",
  "GENRE",
  { "" = ["\n", "COMMENT", "MEDIA", "COUNTRY", "LABEL", "CATALOGNUMBER", "RELEASE_YYYY_MM"] },
  { "" = ["\n", "DISCOGS_URL", "MUSICBRAINZ_URL", "ACCURIPID", "CTDBID", "DISCID"] },
  { "" = ["\n", "DATEADDED", "UNIXTIMEFOOBAR", "UNIXTIMEAPPLE", "UNIXTIMEYOUTUBE"] },
  { "" = ["\n", "MAGNET", "SOURCE"] },
  "\n",
  "*",
  { "\n# -- MusicBraiz Metadata --" = ["MUSICBRAINZ_ALBUMID", "MUSICBRAINZ_ALBUMARTISTID", "MUSICBRAINZ_ARTISTID", "MUSICBRAINZ_RELEASEGROUPID"] },
]

[compress.tracks]
layout = [
  "TRACKNUMBER",
  "TITLE",
  "ARTIST",
  { "# -- MusicBraiz Metadata --" = ["MUSICBRAINZ_TRACKID", "MUSICBRAINZ_RELEASETRACKID"] },
]
