[storage]
library_root = "/home/lewelove/dev/mpf2k-test-library/albums/"
library_export = "~/dev/mpf2k-test-library/metadata_output"

[generate]
supported_extensions = [".flac"]
grouping_keys = ["ALBUMARTIST", "ALBUM", "CUSTOM_ID"]
naming_separator = "_"
naming_sanitization_char = "_"

[compiler]
extensions_folder = "~/dev/mpf2k/extensions/"

[compiler.extensions]
"issue_id" = [
  "COUNTRY", 
  "LABEL", 
  "CATALOGNUMBER", 
  "MEDIA", 
  "COMMENT", 
  "CTDBID", 
  "ACCURIPID", 
  "DISCID"
]

"url" = [
  "DISCOGS_URL", 
  "MUSICBRAINZ_URL"
]

"history" = [
  "UNIX_ADDED_PRIMARY", 
  "UNIX_ADDED_LOCAL", 
  "UNIX_ADDED_FOOBAR", 
  "UNIX_ADDED_APPLEMUSIC", 
  "UNIX_ADDED_YOUTUBE"
]

"custom" = [
  "CUSTOM_ID", 
  "CUSTOM_ALBUMARTIST", 
  "CUSTOM_STRING", 
  "OLD_COMMENT"
]

"musicbrainz" = [
  "MUSICBRAINZ_ALBUMARTISTID", 
  "MUSICBRAINZ_RELEASEGROUPID", 
  "MUSICBRAINZ_ALBUMID", 
  "MUSICBRAINZ_ARTISTID", 
  "MUSICBRAINZ_RELEASETRACKID", 
  "MUSICBRAINZ_TRACKID"
]

"test_logic" = [
  "is_cd"
]

[lock.layout]
album = [
  "\n",
  "ALBUM", 
  "ALBUMARTIST", 
  "DATE", 
  "GENRE", 
  "\n",
  "COMMENT",
  "\n",
  "ORIGINAL_DATE",
  "ORIGINAL_YEAR",
  "ORIGINAL_YYYY_MM",
  "\n",
  "COUNTRY",
  "LABEL",
  "CATALOGNUMBER",
  "RELEASE_DATE",
  "RELEASE_YEAR",
  "RELEASE_YYYY_MM",
  "\n",
  "MEDIA",
  "DISCOGS_URL",
  "MUSICBRAINZ_URL",
  "\n",
  "ACCURIPID",
  "CTDBID",
  "DISCID",
  "\n",
  "date_added",
  "\n",
  "UNIX_ADDED_LOCAL",
  "UNIX_ADDED_FOOBAR", 
  "UNIX_ADDED_APPLEMUSIC",
  "UNIX_ADDED_YOUTUBE",
  "UNIX_ADDED_PRIMARY",
  "\n",
  "CUSTOM_ID",
  "CUSTOM_ALBUMARTIST",
  "CUSTOM_STRING",
  "OLD_COMMENT",
  "\n",
  "album_duration_time",
  "TOTALDISCS",
  "TOTALTRACKS",
  "\n",
  "MUSICBRAINZ_ALBUMID",
  "MUSICBRAINZ_ALBUMARTISTID",
  "MUSICBRAINZ_RELEASEGROUPID",
  "\n",
  "album_root_path",
  "cover_path",
  "unix_added",
  "\n",
  "metadata_toml_mtime",
  "metadata_toml_hash",
  "cover_mtime",
  "cover_byte_size",
  "*",
  "\n",
]

tracks = [
  # "is_cd",
  "TITLE",
  "ARTIST",
  "track_path",
  "TRACKNUMBER",
  "DISCNUMBER",
  "track_duration_time",
  "encoding",
  "sample_rate",
  "bits_per_sample",
  "channels",
  "track_mtime",
  "track_size",
  "track_duration_in_ms",
  "track_duration_in_samples",
  "lyrics_path",
  "track_path_absolute",
  "LYRICS",
  "MUSICBRAINZ_TRACKID",
  "MUSICBRAINZ_RELEASETRACKID",
  "MUSICBRAINZ_ARTISTID",
  "*",
  "\n",
]

[compress.album]
layout = [
  "\n",
  "ALBUM",
  "ALBUMARTIST",
  "DATE",
  "GENRE",
  { "" = ["\n", "COMMENT"] },
  { "" = ["\n", "ORIGINAL_DATE", "ORIGINAL_YEAR", "ORIGINAL_YYYY_MM"] },
  { "" = ["\n", "COUNTRY", "LABEL", "CATALOGNUMBER", "RELEASE_DATE", "RELEASE_YEAR", "RELEASE_YYYY_MM"] },
  { "" = ["\n", "MEDIA", "DISCOGS_URL", "MUSICBRAINZ_URL"] },
  { "" = ["\n", "ACCURIPID", "CTDBID", "DISCID"] },
  { "" = ["\n", "DATEADDED"] },
  { "" = ["\n", "UNIX_ADDED_LOCAL", "UNIX_ADDED_APPLEMUSIC", "UNIX_ADDED_YOUTUBE", "UNIX_ADDED_PRIMARY", "UNIXTIMEFOOBAR", "UNIXTIMEAPPLE", "UNIXTIMEYOUTUBE"] },
  { "" = ["\n", "MAGNET", "SOURCE"] },
  "\n",
  "*",
  { "\n# -- MusicBraiz Metadata --" = ["MUSICBRAINZ_ALBUMID", "MUSICBRAINZ_ALBUMARTISTID", "MUSICBRAINZ_RELEASEGROUPID"] },
]

[compress.tracks]
layout = [
  "TRACKNUMBER",
  "TITLE",
  "ARTIST",
  { "" = ["MUSICBRAINZ_TRACKID", "MUSICBRAINZ_RELEASETRACKID", "MUSICBRAINZ_ARTISTID"] },
]
