[package]
name = "discogs_fetch_master"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
libactions = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["query"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
urlencoding = { workspace = true }
