use crate::compile::builder::context::AlbumContext;
use crate::compile::resolvers::standard;
use image::GenericImageView;
use image::imageops::FilterType;
use palette::{FromColor, Lab, Srgb};
use serde_json::{Value, json};
use std::collections::HashSet;
use std::path::Path;

pub fn resolve_date(ctx: &AlbumContext) -> String {
    ctx.source
        .get("date")
        .or_else(|| ctx.source.get("year"))
        .or_else(|| ctx.source.get("originalyear"))
        .and_then(Value::as_str)
        .unwrap_or("0000")
        .to_string()
}

pub fn resolve_yyyy_mm(ctx: &AlbumContext, key: &str) -> String {
    if let Some(v) = ctx.source.get(key).and_then(Value::as_str) {
        return v.to_string();
    }
    let d = resolve_date(ctx);
    if d.len() >= 4 {
        format!("{}-00", &d[0..4])
    } else {
        "0000-00".to_string()
    }
}

pub fn resolve_genre(ctx: &AlbumContext) -> Vec<String> {
    let raw = ctx.source.get("genre").cloned().unwrap_or(json!(null));
    let mut parts = Vec::new();
    match raw {
        Value::Array(arr) => {
            for v in arr {
                if let Some(s) = v.as_str() {
                    parts.push(s.trim().to_string());
                }
            }
        }
        Value::String(s) => {
            for p in s.split(';') {
                let t = p.trim();
                if !t.is_empty() {
                    parts.push(t.to_string());
                }
            }
        }
        _ => {}
    }
    if parts.is_empty() {
        parts.push("Unknown".to_string());
    }
    let mut seen = HashSet::new();
    parts
        .into_iter()
        .filter(|p| seen.insert(p.clone()))
        .collect()
}

pub fn calculate_total_discs(tracks: &[Value]) -> u32 {
    let mut discs = HashSet::new();
    for t in tracks {
        let val = match t.get("DISCNUMBER") {
            Some(Value::Number(n)) => n.as_u64().unwrap_or(0),
            Some(Value::String(s)) => s
                .split('/')
                .next()
                .unwrap_or("0")
                .parse::<u64>()
                .unwrap_or(0),
            _ => 0,
        };
        if val > 0 {
            discs.insert(val);
        }
    }
    if discs.is_empty() {
        1
    } else {
        u32::try_from(discs.len()).unwrap_or(u32::MAX)
    }
}

pub fn resolve_album_info_unix_added(ctx: &AlbumContext) -> u64 {
    let keys =[
        "unix_added_primary",
        "unixtimeyoutube",
        "unixtimeapple",
        "unixtimefoobar",
        "unix_added_youtube",
        "unix_added_applemusic",
        "unix_added_foobar",
        "unix_added_local",
    ];
    for key in keys {
        if let Some(val) = ctx.source.get(key).and_then(Value::as_str)
            && let Ok(ts) = val.parse::<u64>()
        {
            return ts;
        }
    }
    0
}

pub fn resolve_custom_albumartist(ctx: &AlbumContext) -> String {
    let keys =[
        "custom_albumartist",
        "artistartist",
        "albumartist",
    ];
    for k in keys {
        if let Some(v) = ctx.source.get(k).and_then(Value::as_str) {
            return v.to_string();
        }
    }
    "Unknown".to_string()
}

pub fn rel_path(target: &Path, base: &Path) -> String {
    target.strip_prefix(base).map_or_else(
        |_| target.to_string_lossy().to_string(),
        |p| p.to_string_lossy().to_string(),
    )
}

pub fn resolve_cover_chroma(ctx: &AlbumContext) -> Option<Value> {
    let img = ctx.cover_image?;
    let (width, height) = img.dimensions();
    let total = f64::from(width * height);
    if total == 0.0 {
        return Some(json!(0.0));
    }

    let mut sum_rg = 0.0;
    let mut sum_yb = 0.0;
    let mut sum_sq_rg = 0.0;
    let mut sum_sq_yb = 0.0;

    for p in img.pixels() {
        let r = f64::from(p.2[0]);
        let g = f64::from(p.2[1]);
        let b = f64::from(p.2[2]);
        let rg = (r - g).abs();
        let yb = (0.5f64.mul_add(r + g, -b)).abs();
        sum_rg += rg;
        sum_yb += yb;
        sum_sq_rg += rg * rg;
        sum_sq_yb += yb * yb;
    }

    let m_rg = sum_rg / total;
    let m_yb = sum_yb / total;
    let v_rg = m_rg.mul_add(-m_rg, sum_sq_rg / total);
    let v_yb = m_yb.mul_add(-m_yb, sum_sq_yb / total);
    let std_root = (v_rg.max(0.0) + v_yb.max(0.0)).sqrt();
    let mean_root = m_rg.hypot(m_yb);
    Some(json!(0.3f64.mul_add(mean_root, std_root)))
}

pub fn resolve_cover_entropy(ctx: &AlbumContext) -> Option<Value> {
    let img = ctx.cover_image?;
    let gray = img.grayscale();
    let mut buf = Vec::new();
    let mut cursor = std::io::Cursor::new(&mut buf);
    gray.write_to(&mut cursor, image::ImageFormat::Png).ok()?;
    Some(json!(buf.len()))
}

pub fn resolve_cover_palette(ctx: &AlbumContext) -> Option<Value> {
    // Load the raw original image directly from the physical path instead of using the 
    // downscaled, Lanczos-filtered thumbnail generated by context.
    let cover_path = ctx.cover_path?;
    let img = image::open(ctx.album_root.join(cover_path)).ok()?;
    
    let discovery_img = img.resize_exact(64, 64, FilterType::Nearest);
    let mut discovery_pixels: Vec<Lab> = Vec::new();
    let mut weights: Vec<f32> = Vec::new();

    for (_, _, p) in discovery_img.pixels() {
        let srgb = Srgb::new(p[0] as f32 / 255.0, p[1] as f32 / 255.0, p[2] as f32 / 255.0);
        let lab = Lab::from_color(srgb);
        
        let chroma = (lab.a.powi(2) + lab.b.powi(2)).sqrt();
        let weight = 1.0 + (chroma * 0.15); 
        
        discovery_pixels.push(lab);
        weights.push(weight);
    }

    let sample_size = 1024;
    let step = (discovery_pixels.len() / sample_size).max(1);
    let seeds: Vec<Lab> = discovery_pixels.iter().step_by(step).take(sample_size).copied().collect();

    let mut distances = Vec::new();
    for i in 0..seeds.len() {
        for j in (i + 1)..seeds.len() {
            let p1 = seeds[i];
            let p2 = seeds[j];
            distances.push(((p1.l - p2.l).powi(2) + (p1.a - p2.a).powi(2) + (p1.b - p2.b).powi(2)).sqrt());
        }
    }
    distances.sort_by(|a, b| a.partial_cmp(b).unwrap());
    
    let bandwidth = if distances.is_empty() { 6.0 } else { 
        distances[(distances.len() as f32 * 0.2) as usize].clamp(2.0, 16.0) 
    };
    
    let bandwidth_sq = bandwidth * bandwidth;
    let convergence_sq = 0.1_f32;
    let max_iter = 15;

    let mut raw_modes = Vec::new();
    for &seed in &seeds {
        let mut current = seed;
        for _ in 0..max_iter {
            let (mut sum_l, mut sum_a, mut sum_b, mut total_weight) = (0.0, 0.0, 0.0, 0.0);
            for (idx, p) in discovery_pixels.iter().enumerate() {
                let dist_sq = (p.l - current.l).powi(2) + (p.a - current.a).powi(2) + (p.b - current.b).powi(2);
                if dist_sq <= bandwidth_sq {
                    let w = weights[idx];
                    sum_l += p.l * w;
                    sum_a += p.a * w;
                    sum_b += p.b * w;
                    total_weight += w;
                }
            }
            if total_weight > 0.0 {
                let next = Lab::new(sum_l / total_weight, sum_a / total_weight, sum_b / total_weight);
                let shift_sq = (next.l - current.l).powi(2) + (next.a - current.a).powi(2) + (next.b - current.b).powi(2);
                current = next;
                if shift_sq < convergence_sq { break; }
            } else { break; }
        }
        raw_modes.push(current);
    }

    let mut merged_centers: Vec<Lab> = Vec::new();
    let merge_threshold_sq = 32.0_f32; 

    for mode in raw_modes {
        let mut is_merged = false;
        for center in &merged_centers {
            let dist_sq = (center.l - mode.l).powi(2) + (center.a - mode.a).powi(2) + (center.b - mode.b).powi(2);
            if dist_sq < merge_threshold_sq {
                is_merged = true;
                break;
            }
        }
        if !is_merged { merged_centers.push(mode); }
    }

    let ratio_img = img.resize_exact(256, 256, FilterType::Nearest);
    let mut physical_counts = vec![0_usize; merged_centers.len()];
    let mut ratio_labels = Vec::new();

    for (_, _, p) in ratio_img.pixels() {
        let pixel_lab = Lab::from_color(Srgb::new(p[0] as f32 / 255.0, p[1] as f32 / 255.0, p[2] as f32 / 255.0));
        let mut best_dist = f32::MAX;
        let mut best_idx = 0;
        for (idx, center_lab) in merged_centers.iter().enumerate() {
            let dist_sq = (pixel_lab.l - center_lab.l).powi(2) + (pixel_lab.a - center_lab.a).powi(2) + (pixel_lab.b - center_lab.b).powi(2);
            if dist_sq < best_dist {
                best_dist = dist_sq;
                best_idx = idx;
            }
        }
        physical_counts[best_idx] += 1;
        ratio_labels.push(best_idx);
    }

    let total_samples = 256.0 * 256.0;
    let ratios: Vec<f64> = physical_counts.iter().map(|&c| c as f64 / total_samples).collect();

    let mut sorted_indices: Vec<usize> = (0..merged_centers.len()).collect();
    sorted_indices.sort_by(|&a, &b| ratios[b].partial_cmp(&ratios[a]).unwrap());

    let palette_data: Vec<Value> = sorted_indices
        .into_iter()
        .map(|idx| {
            let ratio = ratios[idx];
            let lab = merged_centers[idx];
            let srgb = Srgb::from_color(lab);
            let hex = format!(
                "#{:02X}{:02X}{:02X}",
                (srgb.red.clamp(0.0, 1.0) * 255.0).round() as u8,
                (srgb.green.clamp(0.0, 1.0) * 255.0).round() as u8,
                (srgb.blue.clamp(0.0, 1.0) * 255.0).round() as u8
            );

            json!([hex, format!("{ratio:.4}")])
        })
        .collect();

    Some(json!(palette_data))
}

pub fn resolve_comment(ctx: &AlbumContext) -> String {
    if let Some(v) = ctx.source.get("comment").and_then(Value::as_str)
        && !v.is_empty()
    {
        return v.to_string();
    }

    let country = standard::get_raw(ctx.source, "country", "");
    let label = standard::get_raw(ctx.source, "label", "");
    let cat = standard::get_raw(ctx.source, "catalognumber", "");
    if country.is_empty() && label.is_empty() && cat.is_empty() {
        return String::new();
    }
    let yyyy_mm = resolve_yyyy_mm(ctx, "release_yyyy_mm");
    let year = if yyyy_mm.len() >= 4 {
        &yyyy_mm[0..4]
    } else {
        ""
    };
    
    let parts =[
        year,
        &country,
        &label,
        &cat,
    ];

    parts
        .iter()
        .filter(|s| !s.is_empty())
        .copied()
        .collect::<Vec<_>>()
        .join(" ")
}

pub fn resolve_lyrics_path(
    album_root: &Path,
    track_num: u32,
    disc_num: u32,
    total_discs: u32,
) -> Option<String> {
    let folders =[
        "lyrics",
        "Lyrics",
    ];
    let mut candidates = Vec::new();

    for folder in folders {
        let dir = album_root.join(folder);
        let Ok(entries) = std::fs::read_dir(dir) else {
            continue;
        };

        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            if !path.is_file() {
                continue;
            }

            let Some(ext) = path
                .extension()
                .and_then(|e| e.to_str())
                .map(str::to_lowercase)
            else {
                continue;
            };
            if ext != "lrc" && ext != "txt" {
                continue;
            }

            let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };

            let is_match = if total_discs > 1 {
                name.find('.').is_some_and(|dot_idx| {
                    let disc_part = &name[..dot_idx];
                    let remaining = &name[dot_idx + 1..];
                    let track_part = remaining
                        .chars()
                        .take_while(char::is_ascii_digit)
                        .collect::<String>();

                    let d_match = disc_part.parse::<u32>().is_ok_and(|d| d == disc_num);
                    let t_match = track_part.parse::<u32>().is_ok_and(|t| t == track_num);
                    d_match && t_match
                })
            } else {
                let track_part = name
                    .chars()
                    .take_while(char::is_ascii_digit)
                    .collect::<String>();
                track_part.parse::<u32>().is_ok_and(|t| t == track_num)
            };

            if is_match {
                candidates.push((rel_path(&path, album_root), ext));
            }
        }
    }

    if candidates.is_empty() {
        return None;
    }

    if let Some(lrc) = candidates.iter().find(|(_, ext)| ext == "lrc") {
        return Some(lrc.0.clone());
    }

    candidates.first().map(|(path, _)| path.clone())
}
