[filters.all]
label = "All"
sql.where = "1=1"

[groupers.genre]
label = "Genre"
sql.select = "json_extract(metadata, '$.album.genre')"

[groupers.artists]
label = "Artists"
index = true
sql.select = "COALESCE(NULLIF(json_extract(metadata, '$.album.tags.artists'), '[]'), json_extract(metadata, '$.album.albumartist'))"

[groupers.decade]
label = "Decade"
sql.select = "substr(json_extract(metadata, '$.album.date'), 1, 3) || '0s'"

[groupers.total_tracks]
label = "Total Tracks"
sql.select = "CAST(json_extract(metadata, '$.album.info.total_tracks') AS TEXT)"

[groupers.total_discs]
label = "Total Discs"
sql.select = "CAST(COALESCE(json_extract(metadata, '$.album.info.total_discs'), 1) AS TEXT)"

[groupers.year_added]
label = "Year Added"
sql.select = "substr(json_extract(metadata, '$.album.info.date_added'), 1, 4)"

[groupers.chroma]
label = "Chroma"
sql.select = "CASE WHEN CAST(json_extract(metadata, '$.album.tags.cover_chroma') AS FLOAT) = 0 THEN 'Monochrome' WHEN CAST(json_extract(metadata, '$.album.tags.cover_chroma') AS FLOAT) < 15 THEN 'Bleak' WHEN CAST(json_extract(metadata, '$.album.tags.cover_chroma') AS FLOAT) < 33 THEN 'Muted' WHEN CAST(json_extract(metadata, '$.album.tags.cover_chroma') AS FLOAT) < 60 THEN 'Standard' ELSE 'Vibrant' END"

[orders.default]
label = "Default"
sql.order_by = "CASE WHEN LOWER(COALESCE(json_extract(metadata, '$.album.tags.custom_albumartist'), json_extract(metadata, '$.album.albumartist'))) LIKE 'the %' THEN SUBSTR(COALESCE(json_extract(metadata, '$.album.tags.custom_albumartist'), json_extract(metadata, '$.album.albumartist')), 5) ELSE COALESCE(json_extract(metadata, '$.album.tags.custom_albumartist'), json_extract(metadata, '$.album.albumartist')) END ASC, json_extract(metadata, '$.album.date') ASC, json_extract(metadata, '$.album.album') ASC"

[orders.az]
label = "Alphabetical"
sql.order_by = "json_extract(metadata, '$.album.album') ASC"

[orders.year]
label = "Year"
sql.order_by = "json_extract(metadata, '$.album.date') DESC"

[orders.duration]
label = "Duration"
sql.order_by = "CAST(json_extract(metadata, '$.album.info.album_duration') AS INT) DESC"

[orders.chroma]
label = "Chroma"
sql.order_by = "CAST(json_extract(metadata, '$.album.tags.cover_chroma') AS FLOAT) DESC"

[orders.entropy]
label = "Entropy"
sql.order_by = "CAST(json_extract(metadata, '$.album.tags.cover_entropy') AS INT) DESC"

[orders.date_added]
label = "Date Added"
sql.order_by = "json_extract(metadata, '$.album.info.date_added') DESC"

[orders.last_edited]
label = "Last Edited"
sql.order_by = "COALESCE(json_extract(metadata, '$.album.info.metadata_toml_mtime'), 0) DESC"

[libraries.library]
label = "Entire Library"
filters = ["all"]
sql.where = "1=1"

[shelves.recently_added]
label = "Recently Added"
sql.where = "1=1"
sql.order_by = "json_extract(metadata, '$.album.info.date_added') DESC"
