use slint::{Model, VecModel, SharedString}; // SharedString is Slint's string type
use std::rc::Rc;
use serde::Deserialize;
use std::fs;
use std::path::Path;

// This macro pulls in everything generated by build.rs
slint::include_modules!();

#[derive(Debug, Deserialize)]
struct LockFile {
    album: AlbumInfo,
}

#[derive(Debug, Deserialize)]
#[allow(non_snake_box)] // Matches your uppercase TOML/JSON keys
struct AlbumInfo {
    ALBUM: String,
    ALBUMARTIST: String,
    cover_hash: Option<String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let ui = MainWindow::new()?;

    // --- LOGIC: Load your actual albums ---
    // POINT THIS to your library root
    let library_root = "/home/lewelove/dev/vellum/test_library"; 
    
    let mut album_data_list = Vec::new();

    if let Ok(entries) = fs::read_dir(library_root) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let lock_path = path.join("metadata.lock.json");
                if lock_path.exists() {
                    if let Ok(content) = fs::read_to_string(lock_path) {
                        if let Ok(data) = serde_json::from_str::<LockFile>(&content) {
                            // Map the JSON data to the Slint struct
                            album_data_list.push(AlbumData {
                                title: SharedString::from(data.album.ALBUM),
                                artist: SharedString::from(data.album.ALBUMARTIST),
                                cover_hash: SharedString::from(data.album.cover_hash.unwrap_or_default()),
                            });
                        }
                    }
                }
            }
        }
    }

    // Fallback if no albums found so the grid isn't empty
    if album_data_list.is_empty() {
        for i in 1..=12 {
            album_data_list.push(AlbumData {
                title: format!("Test Album {}", i).into(),
                artist: "Native Artist".into(),
                cover_hash: "".into(),
            });
        }
    }

    // Feed the data to Slint
    let model = Rc::new(VecModel::from(album_data_list));
    ui.set_albums(model.into());

    ui.run()?;
    Ok(())
}
