[compiler_registry]

album = { level = "album" }
albumartist = { level = "album" }
date = { level = "album" }
genre = { level = "album" }
comment = { level = "album" }
original_date = { level = "album" }
original_year = { level = "album" }
original_yyyy_mm = { level = "album" }
release_date = { level = "album" }
release_year = { level = "album" }
release_yyyy_mm = { level = "album" }
country = { level = "album" }
label = { level = "album" }
catalognumber = { level = "album" }
media = { level = "album" }
discogs_url = { level = "album" }
musicbrainz_url = { level = "album" }
unix_added_local = { level = "album" }
unix_added_foobar = { level = "album" }
unix_added_applemusic = { level = "album" }
unix_added_youtube = { level = "album" }
unix_added_primary = { level = "album" }
custom_id = { level = "album" }
custom_albumartist = { level = "album" }
custom_string = { level = "album" }
old_comment = { level = "album" }
replaygain_album_gain = { level = "album" }
replaygain_album_peak = { level = "album" }
musicbrainz_albumid = { level = "album" }
musicbrainz_albumartistid = { level = "album" }
musicbrainz_releasegroupid = { level = "album" }
cover_chroma = { level = "album", sync = false }
cover_entropy = { level = "album", sync = false }

title = { level = "tracks" }
artist = { level = "tracks" }
tracknumber = { level = "tracks" }
discnumber = { level = "tracks" }
lyrics = { level = "tracks" }
accuripid = { level = "tracks" }
ctdbid = { level = "tracks" }
discid = { level = "tracks" }
replaygain_track_gain = { level = "tracks" }
replaygain_track_peak = { level = "tracks" }
musicbrainz_trackid = { level = "tracks" }
musicbrainz_releasetrackid = { level = "tracks" }
musicbrainz_artistid = { level = "tracks" }
