[lock.layout]

album = [
  "\n",
  "ALBUM",
  "ALBUMARTIST",
  "DATE",
  "GENRE",
  "\n",
  "COMMENT",
  "\n",
  "ORIGINAL_DATE",
  "ORIGINAL_YEAR",
  "ORIGINAL_YYYY_MM",
  "RELEASE_DATE",
  "RELEASE_YEAR",
  "RELEASE_YYYY_MM",
  "\n",
  "COUNTRY",
  "LABEL",
  "CATALOGNUMBER",
  "MEDIA",
  "\n",
  "DISCOGS_URL",
  "MUSICBRAINZ_URL",
  "\n",
  "date_added",
  "unix_added",
  "UNIX_ADDED_LOCAL",
  "UNIX_ADDED_FOOBAR",
  "UNIX_ADDED_APPLEMUSIC",
  "UNIX_ADDED_YOUTUBE",
  "UNIX_ADDED_PRIMARY",
  "\n",
  "CUSTOM_ID",
  "CUSTOM_ALBUMARTIST",
  "CUSTOM_STRING",
  "OLD_COMMENT",
  "\n",
  "album_duration_time",
  "album_duration_in_ms",
  "total_discs",
  "total_tracks",
  "\n",
  "cover_chroma",
  "cover_entropy",
  "\n",
  "REPLAYGAIN_ALBUM_GAIN",
  "REPLAYGAIN_ALBUM_PEAK",
  "\n",
  "MUSICBRAINZ_ALBUMID",
  "MUSICBRAINZ_ALBUMARTISTID",
  "MUSICBRAINZ_RELEASEGROUPID",
  "\n",
  "album_root_path",
  "cover_path",
  "cover_hash",
  "cover_mtime",
  "cover_byte_size",
  "\n",
  "metadata_toml_mtime",
  "metadata_toml_hash",
  "file_tag_subset_match"
]

tracks = [
  "TITLE",
  "ARTIST",
  "track_path",
  "TRACKNUMBER",
  "DISCNUMBER",
  "ACCURIPID",
  "CTDBID",
  "DISCID",
  "track_duration_time",
  "encoding",
  "sample_rate",
  "bits_per_sample",
  "channels",
  "track_mtime",
  "track_size",
  "track_duration_in_ms",
  "track_library_path",
  "LYRICS",
  "lyrics_path",
  "REPLAYGAIN_TRACK_GAIN",
  "REPLAYGAIN_TRACK_PEAK",
  "MUSICBRAINZ_TRACKID",
  "MUSICBRAINZ_RELEASETRACKID",
  "MUSICBRAINZ_ARTISTID"
]

