[package]
name = "get_theme"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
libactions = { workspace = true }
anyhow = { workspace = true }
image = { workspace = true }
kmeans_colors = { workspace = true }
palette = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
